### ISSUE TITLE
Model Size, Computation and Training time

### ISSUE THREAD

**Issue by yugeshav** [earthspecies/cocktail-party-problem#2]
Hello

Please let me know the model size (MB/ KB), Training time (for 100hrs on some vm config) and computation(CPU).

Any other benchmarking available please post here

Regards
Yugesh

**Comment by pcbermant** [comment]
The models were trained on a high-compute VM using a single NVIDIA P100 GPU. More details regarding available benchmarking (e.g. model sizes) can be found in the paper https://www.nature.com/articles/s41598-021-02790-2. Hope this helps.
