### ISSUE TITLE
details on data structure of downloaded data?

### ISSUE THREAD

**Issue by thejasvibr** [earthspecies/cocktail-party-problem#5]
The ```README``` states 'Download the bioacoustic datasets into a directory ```BioacousticData/```' - how should the data 'look' (how many folders down should one go and copy the downloaded data into this BioacousticData folder?). Could you please provide more detail in the ```README```?

**Comment by pcbermant** [comment]
I updated the README. You can download them with the name AnimalName/ under the BioacousticData/ root.
